### ISSUE TITLE
the proof verification is temporarily unavailable

### ISSUE THREAD

**Issue by devrajsinghrawat** [matter-labs/zinc#4]
Hi Team,

I am trying to run the example mentioned in the below link 

https://zinc.zksync.io/08-circuits/02-minimal-example.html

and got the below error at this command 
`zargo prove > proof.txt`

`[ERROR zargo] the proof verification is temporarily unavailable`

**Comment by hedgar2017** [comment]
Hi!Sorry, this chapter of the book is outdated and relevant to the version <=0.1.5 only.In >=0.2.0 proof verification does not work, as we move to another concept.Best wishes! Sent from Mail for Windows 10 From: Dev-DSent: Thursday, January 14, 2021 14:23To: matter-labs/zincCc: SubscribedSubject: [matter-labs/zinc] the proof verification is temporarily unavailable (#4) Hi Team,I am trying to run the example mentioned in the below linkhttps://zinc.zksync.io/08-circuits/02-minimal-example.htmland got the below error at this commandzargo prove > proof.txt[ERROR zargo] the proof verification is temporarily unavailable—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by devrajsinghrawat** [comment]
Hi @hedgar2017 thanks for the prompt response .

**Comment by hedgar2017** [comment]
@devrajsinghrawat np, sorry for the email formatting.
